export const TempGridData: any[] = [
    {
        name: "John Smith",
        age: 32,
        gender: "Male",
        city: "New York",
        country: "USA",
        occupation: "Software Engineer",
        hobbies: "Reading, Watching movies",
        marital_status: "Married",
        education: "Bachelor's Degree in Computer Science",
        languages: "English, Spanish"
    },
    {
        name: "Mary Johnson",
        age: 28,
        gender: "Female",
        city: "London",
        country: "UK",
        occupation: "Marketing Manager",
        hobbies: "Traveling, Photography",
        marital_status: "Single",
        education: "Master's Degree in Business Administration",
        languages: "English, French"
    },
    {
        name: "David Lee",
        age: 40,
        gender: "Male",
        city: "Singapore",
        country: "Singapore",
        occupation: "Investment Banker",
        hobbies: "Playing Tennis, Watching TV Shows",
        marital_status: "Married",
        education: "Bachelor's Degree in Economics",
        languages: "English, Mandarin"
    },
    {
        name: "Ana Gomez",
        age: 25,
        gender: "Female",
        city: "Madrid",
        country: "Spain",
        occupation: "Graphic Designer",
        hobbies: "Drawing, Listening to Music",
        marital_status: "Single",
        education: "Bachelor's Degree in Graphic Design",
        languages: "Spanish, English"
    },
    {
        name: "Kim Sung",
        age: 30,
        gender: "Female",
        city: "Seoul",
        country: "South Korea",
        occupation: "Translator",
        hobbies: "Reading, Cooking",
        marital_status: "Married",
        education: "Bachelor's Degree in Translation and Interpretation",
        languages: "Korean, English, Chinese"
    },
    {
        name: "Michael Johnson",
        age: 37,
        gender: "Male",
        occupation: "Marketing Manager",
        hobbies: "Running, playing guitar, watching sports",
        address: "987 Pine St, Anytown, USA",
        phone: "555-7890",
        email: "michael.johnson@example.com",
        favorite_color: "Black",
        favorite_food: "Burgers"
    },
    {
        name: "Emily Chen",
        age: 28,
        gender: "Female",
        occupation: "Data Analyst",
        hobbies: "Playing piano, cooking, yoga",
        address: "321 Elm St, Anytown, USA",
        phone: "555-3456",
        email: "emily.chen@example.com",
        favorite_color: "Purple",
        favorite_food: "Thai Curry"
    },
    {
        name: "Jane Smith",
        age: 25,
        gender: "Female",
        occupation: "Graphic Designer",
        hobbies: "Painting, watching movies, traveling",
        address: "456 Oak St, Anytown, USA",
        phone: "555-5678",
        email: "jane.smith@example.com",
        favorite_color: "Green",
        favorite_food: "Sushi"
    },
    {
        name: "John Doe",
        age: 30,
        gender: "Male",
        occupation: "Software Developer",
        hobbies: "Reading, playing video games, hiking",
        address: "123 Main St, Anytown, USA",
        phone: "555-1234",
        email: "john.doe@example.com",
        favorite_color: "Blue",
        favorite_food: "Pizza"
    },
    {
        name: "Yui Nakamura",
        age: 32,
        gender: "Female",
        occupation: "Teacher",
        hobbies: "Playing piano, watching movies, traveling",
        address: "1-1-1 Shinjuku, Tokyo, Japan",
        phone: "+81 3-XXXX-XXXX",
        email: "yui.nakamura@example.com",
        favorite_color: "Pink",
        favorite_food: "Sushi"
    },
    {
        name: "Ryo Tanaka",
        age: 29,
        gender: "Male",
        occupation: "Engineer",
        hobbies: "Playing video games, watching anime, cooking",
        address: "2-2-2 Shibuya, Tokyo, Japan",
        phone: "+81 3-XXXX-XXXX",
        email: "ryo.tanaka@example.com",
        favorite_color: "Blue",
        favorite_food: "Ramen"
    },
    {
        name: "Sakura Yamamoto",
        age: 26,
        gender: "Female",
        occupation: "Graphic Designer",
        hobbies: "Drawing, hiking, listening to music",
        address: "3-3-3 Shinagawa, Tokyo, Japan",
        phone: "+81 3-XXXX-XXXX",
        email: "sakura.yamamoto@example.com",
        favorite_color: "Green",
        favorite_food: "Tempura"
    },
    {
        name: "Hiroshi Sato",
        age: 35,
        gender: "Male",
        occupation: "Businessman",
        hobbies: "Playing golf, reading, watching baseball",
        address: "4-4-4 Chiyoda, Tokyo, Japan",
        phone: "+81 3-XXXX-XXXX",
        email: "hiroshi.sato@example.com",
        favorite_color: "Black",
        favorite_food: "Soba"
    },
    {
        name: "Aiko Fujimoto",
        age: 30,
        gender: "Female",
        occupation: "Doctor",
        hobbies: "Swimming, playing tennis, traveling",
        address: "5-5-5 Minato, Tokyo, Japan",
        phone: "+81 3-XXXX-XXXX",
        email: "aiko.fujimoto@example.com",
        favorite_color: "Red",
        favorite_food: "Udon"
    },
    {
        name: "Taro Yamamoto",
        age: 32,
        gender: "Male",
        occupation: "Engineer",
        hobbies: "Playing video games, watching anime, cooking",
        address: "1-1-1 Shinjuku, Tokyo, Japan",
        phone: "+81-3-1234-5678",
        email: "taro.yamamoto@example.com",
        favorite_color: "Blue",
        favorite_food: "Sushi"
    },
    {
        name: "Sakura Nakamura",
        age: 27,
        gender: "Female",
        occupation: "Teacher",
        hobbies: "Playing piano, hiking, reading",
        address: "2-2-2 Shibuya, Tokyo, Japan",
        phone: "+81-3-2345-6789",
        email: "sakura.nakamura@example.com",
        favorite_color: "Pink",
        favorite_food: "Ramen"
    },
    {
        name: "Kazuki Sato",
        age: 40,
        gender: "Male",
        occupation: "Architect",
        hobbies: "Fishing, playing golf, traveling",
        address: "3-3-3 Roppongi, Tokyo, Japan",
        phone: "+81-3-3456-7890",
        email: "kazuki.sato@example.com",
        favorite_color: "Green",
        favorite_food: "Tempura"
    },
    {
        name: "Aiko Tanaka",
        age: 25,
        gender: "Female",
        occupation: "Graphic Designer",
        hobbies: "Drawing, listening to music, watching movies",
        address: "4-4-4 Shinagawa, Tokyo, Japan",
        phone: "+81-3-4567-8901",
        email: "aiko.tanaka@example.com",
        favorite_color: "Purple",
        favorite_food: "Okonomiyaki"
    },
    {
        name: "Shinichi Kimura",
        age: 35,
        gender: "Male",
        occupation: "Sales Manager",
        hobbies: "Playing soccer, reading manga, watching TV",
        address: "5-5-5 Ginza, Tokyo, Japan",
        phone: "+81-3-5678-9012",
        email: "shinichi.kimura@example.com",
        favorite_color: "Red",
        favorite_food: "Udon"
    }
];
